# See: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#about-the-dependabotyml-file
version: 2

updates:
  # Configure check for outdated GitHub Actions actions in workflows and action metadata.
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/dependabot/README.md
  # See: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: github-actions
    assignees:
      - per1234
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
  - package-ecosystem: npm
    assignees:
      - per1234
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
  - package-ecosystem: pip
    assignees:
      - per1234
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
