name: libraries/compile-examples workflow

on:
  pull_request:
    paths:
      - '.github/workflows/libraries_compile-examples.yml'
      - 'libraries/compile-examples/**'

  push:
    paths:
      - '.github/workflows/libraries_compile-examples.yml'
      - 'libraries/compile-examples/**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHON_PROJECT_PATH: ${GITHUB_WORKSPACE}/compilesketches
      PYTHON_PROJECT_TESTS_PATH: ${GITHUB_WORKSPACE}/compilesketches/tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement "${{ env.PYTHON_PROJECT_TESTS_PATH }}/requirements.txt"

      - name: Lint with flake8
        run: |
          pip install --quiet flake8
          pip install --quiet pep8-naming
          flake8 --config "${{ env.PYTHON_PROJECT_PATH }}/.flake8" --show-source "${{ env.PYTHON_PROJECT_PATH }}"

      - name: Run Python unit tests and report code coverage
        run: |
          export PYTHONPATH="${{ env.PYTHON_PROJECT_PATH }}"
          coverage run --source="${{ env.PYTHON_PROJECT_PATH }}" --module pytest "${{ env.PYTHON_PROJECT_TESTS_PATH }}"
          # Display code coverage report in workflow run log
          coverage report

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
